### ISSUE TITLE
Errors during compile

### ISSUE THREAD

**Issue by ScallyBag** [TerjeKir/weiss#156]
Hi,

I’m compiling your engine on a Raspberry Pi and until recently all has been good.

Today I compiled your latest code, and get these errors:
transposition.c:59:12: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘size_t {aka unsigned int}’ [-Wformat=]
     printf("HashTable init complete with %" PRIu64 " entries, using %" PRIu64 "MB.\n", TT.count, MB);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from types.h:5:0,
                 from makemove.h:5,
                 from transposition.c:7:
/usr/include/inttypes.h:105:34: note: format string is defined here
 \# define PRIu64  __PRI64_PREFIX "u"

I still get a binary, but I no longer get your ‘HashTable init’  on manual start-up via ./weiss

Before transposition.c changes:

Al@PicoChess:~ $ ./weiss98
HashTable init complete with 2097152 entries, using 32MB.
uci
id name weiss 0.8-dev
id author Terje Kirstihagen
option name Hash type spin default 32 min 4 max 16384
option name SyzygyPath type string default <empty>
option name Ponder type check default false
uciok

After transposition.c changes:

Al@PicoChess:~/weiss/src $ ./weiss
uci 
id name weiss 0.8-dev
id author Terje Kirstihagen
option name Hash type spin default 32 min 4 max 16384
option name SyzygyPath type string default <empty>
option name Ponder type check default false
uciok

Thanks

Alan Cooper

**Comment by TerjeKir** [comment]
Hello,

I had incorrectly assumed size_t would be 64 bits everywhere weiss would be used. If you could try to compile this branch and let me know how it goes that would be much appreciated: https://github.com/TerjeKir/weiss/tree/Support32bitSizeT

As for the missing initialization message, that was changed in #151 to happen after the first 'isready' is sent to weiss in order to avoid allocating the default hash size only to have to reallocate it if the user specifies a size. Now it waits for 'isready' and inits with the requested size, or default if there was no request.

Thanks for your interest in this project!

Terje Kirstihagen

**Comment by ScallyBag** [comment]
Hi Terje,

Thanks for looking into this for me, I’m afraid there’s no change:

Al@PicoChess:~/weissAlt $ git remote show origin
* remote origin
  Fetch URL: https://github.com/TerjeKir/weiss
  Push  URL: https://github.com/TerjeKir/weiss
  HEAD branch: master
  Remote branches:
    CLOP              tracked
    ChangeTTIndex     tracked
    Improving         tracked
    LazyEval          tracked
    Support32bitSizeT tracked
    master            tracked
    v0.8              tracked
  Local branches configured for 'git pull':
    Support32bitSizeT merges with remote Support32bitSizeT
    master            merges with remote master
  Local refs configured for 'git push':
    Support32bitSizeT pushes to Support32bitSizeT (up to date)
    master            pushes to master            (up to date)
Al@PicoChess:~/weissAlt $ cd src
Al@PicoChess:~/weissAlt/src $ make clean
make: *** No rule to make target 'clean'.  Stop.
Al@PicoChess:~/weissAlt/src $ make -j4
gcc -std=gnu11 -Wall -Wextra -Wshadow -O3 -flto -march=native *.c fathom/tbprobe.c -pthread -lm -o weiss
transposition.c: In function ‘InitTT’:
transposition.c:47:16: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘size_t {aka unsigned int}’ [-Wformat=]
         printf("Allocating %" PRIu64 "MB for the transposition table failed.\n", MB);
                ^~~~~~~~~~~~~~
uci.c: In function ‘UCISetoption’:
uci.c:116:16: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘size_t {aka unsigned int}’ [-Wformat=]
         printf("Hash will use %" PRIu64 "MB after next 'isready'.\n", TT.requestedMB);
                ^~~~~~~~~~~~~~~~~
Al@PicoChess:~/weissAlt/src $

Al.

**Comment by TerjeKir** [comment]
Hi,

I forgot to update it in those two places, but at least it doesn't give errors for the line I did change. I've updated the same branch fixing the remaining two. Please try to compile it again. 

If you could also compile master and see if it works in normal use despite the errors (I would assume it does) that would be great. Remember 'isready' before 'go' if you use it manually. If it does indeed work despite the errors I'm a bit reluctant to add extra code to fix it as the warnings, only happening on 32bit OSs, should be very rare. 

Somewhat related; while googling for information on the issue I found that RPI 3 and 4 have 64bit hardware, but still use 32bit OS as default. If yours is either 3 or 4 you could probably get significantly better performance, especially for chess engines which use 64bit ints a lot, by changing to a 64bit OS. It would also avoid the errors related to size_t being small :)

Terje Kirstihagen

**Comment by ScallyBag** [comment]
Hi Terje,

Yes that’s sorted it no compiler errors.

The binary compiled from your master works too, it just reports different HashTable values:

Al@PicoChess:~ $ cd ~/weiss/src
Al@PicoChess:~/weiss/src $ ./weiss
uci
id name weiss 0.8-dev
id author Terje Kirstihagen
option name Hash type spin default 32 min 4 max 16384
option name SyzygyPath type string default <empty>
option name Ponder type check default false
uciok
isready
HashTable init complete with 32 entries, using 9119396925932568576MB.
Compiled for Picochess by Scally
readyok
quit
Al@PicoChess:~/weiss/src $ cd ~/weissAlt/src
Al@PicoChess:~/weissAlt/src $ ./weiss
uci
id name weiss 0.8-dev
id author Terje Kirstihagen
option name Hash type spin default 32 min 4 max 16384
option name SyzygyPath type string default <empty>
option name Ponder type check default false
uciok
isready
HashTable init complete with 2097152 entries, using 32MB.
Compiled for Picochess by Scally
readyok
quit
Al@PicoChess:~/weissAlt/src $

We use the official Raspbian which is still 32 bit, I have tried unofficial 64 bit versions, but in the end Picochess and the DGT Pi that Incorporates it, is using 32 bit.

Thanks for your help.

Alan Cooper aka Scally.

**Comment by TerjeKir** [comment]
Hi,

could you run the benchmark with each of the compiles to see if they differ? 
`./weiss bench`

Terje Kirstihagen

**Comment by ScallyBag** [comment]
Hi,

There’s no significant difference:

Normal
———-
Benchmark complete:
Time : 37380ms
Nodes: 20984976
NPS  : 561395
Al@PicoChess:~/weiss/src $


32 bit fix
————
Benchmark complete:
Time : 37422ms
Nodes: 20984976
NPS  : 560765
Al@PicoChess:~/weissAlt/src $

Al.

**Comment by TerjeKir** [comment]
Hi,

the 32 bit fix has been merged and is now part of master. #159 

Thank you for the feedback and help solving the problem.

Terje Kirstihagen
