### ISSUE TITLE
clang issues

### ISSUE THREAD

**Issue by theo77186** [TerjeKir/weiss#260]
I've tried to compile Weiss with clang but the build crashed. I've found the cause of the crash. The function `LandingSquareBB` called by `InitBitMasks` relies on the fact that `InitDistance` is called. But as `__attribute__((constructor))` doesn't guarantee any order of call, it's possible that `LandingSquareBB` is called before the distance array is even initialized.

After fixing that, the benches are different because of [this](https://github.com/TerjeKir/weiss/blob/master/src/search.c#L44-L49). When either `depth` or `moves` is zero, the result will be +-inf which converted to int is undefined behavior thus causing the bench differences. I've found a way to fix this while being non-functional for gcc.

Additionally, there are some other undefined behaviors as tested by `-fsanitize=undefined` and gcc refuses to compile Weiss with no optimization.

**edit 1**: I've created a [branch](https://github.com/theo77186/weiss/tree/clang-fix) for this

**Comment by TerjeKir** [comment]
Thank you very much for the help, much appreciated!

Fixed in #261
