### ISSUE TITLE
connect to tablebase website ?

### ISSUE THREAD

**Issue by tissatussa** [TerjeKir/weiss#497]
Congratulations with your strong Weiss engine !  I did several tests and it performs very well !  And it's only 108 Kb !!?

It also has the option to use NoobBook (when connected to internet), which is unique .. few engines have this feature !

One test game was against the very strong SF Crystal v3.2 NNUE, some StockFish clone (see https://github.com/jhellis3/Stockfish/tree/crystal ) : Weiss v1.5-dev almost managed to draw that game : in the very end it made some weak moves (65...Nc5??) and lost .. i attached that game PGN .. the concerning position -see screenshots- ( 8/8/n7/P3Pk2/8/6Bp/5K2/8 b - - 0 1 ) has 7 pieces, so i checked the tablebase at https://www.chessabc.com/en/tablebase and indeed it should be a draw ..

can you create a connection to a tablebase website, just as you connect to NoobBook for openings ?

[Crystal-vs-Weiss_PGN.zip](https://github.com/TerjeKir/weiss/files/6816943/Crystal-vs-Weiss_PGN.zip)

![Screenshot_2021-07-14_13-00-03](https://user-images.githubusercontent.com/1109281/125643712-0c57fc5b-0f9c-4365-8312-cab4194b1b6a.png)

![Screenshot_2021-07-14_13-05-55](https://user-images.githubusercontent.com/1109281/125643859-bc00fb7a-c184-411a-b30b-084c01a30cbc.png)

**Comment by TerjeKir** [comment]
Hey, I'm happy to see your interest in Weiss, and I will see what I can do about probing Syzygy online, it's a good idea!

As a small note I'd recommend calling Crystal a fork; clone often has some bad connotations, and Crystal is a nice, honest project :)

**Comment by tissatussa** [comment]
thanks!

indeed 'fork' is better then 'clone'.

about the NoobBook feature : in the README you could mention an internet connection is needed for it (although it should be obvious).

i never use a Syzygy option for any engine (i use CuteChess for testing engines) because i do not have those large tablebase files .. the idea of an online connection to some tablebase came to me due to your NoobBook feature (which i never encountered at any engine !?) and the fact you mentioned Weiss is not very good at endings (where did i read that?).

i have some other suggestions .. i should create a new "issue" for those .. but i can mention one issue here : could you extend the version numbering ?  I see the past days you created some small changes but it's still called v1.5-dev -- and the GitHub page even mentions "v1.4 latest" !?

**Comment by TerjeKir** [comment]
Thanks for the feedback, I'll mention an internet connection is required for noobbook and online syzygy.

I noted weiss is bad at endgames without syzygy in the 1.4 release :)

Updating the version for each commit is too much of a hassle (and I'd forget it all the time), sorry. Every version between 1.4 and the upcoming 1.5 release will be named 1.5-dev. You can add the date you compile it to the version to separate them if you want :)

**Comment by TerjeKir** [comment]
I have added online syzygy query, please let me know if there are any issues with it! 

(I noticed if weiss plays vs itself with both using it, it queries too often and lichess refuses to respond sometimes, but should be fine as long as opponent isn't moving instantly as well)

**Comment by tissatussa** [comment]
very nice !  I tested the position which i mentioned in this issue, playing against SF Crystal v3.2 NNUE (White) and indeed Weiss v1.5 dev instantly plays Nb4  -not Nc5-  and made the draw !  I guess you can close this issue now.
