### ISSUE TITLE
dynamic piece square tables ?

### ISSUE THREAD

**Issue by tissatussa** [TerjeKir/weiss#498]
i'm not a chess engine programmer myself, but i'm a chess fanatic and a web developer / programmer .. i do no C / C++ but mostly PHP and Python (and only Linux) .. i also gather chess engines and test them with CuteChess by letting them play against eachother and watch the game :-)  In the meantime i learned many things about chess engine programming (in general) and i gave extended feedback to some engine creators, like Wasp, Halogen, RofChade, DON and more ..

i think your Weiss engine is rather special : it's strong, it has no NN(UE), it reaches high depth rather quickly and is only 108 Kb !

one of the main "ingredients" of a chess engine are the "piece square tables" .. i found in general those appear in 2 types : for the middle game and for the end game .. in your file psqt.c i see only 1 table (am i right?) .. i wonder : could it be possible & good to have different piece square tables, even dynamically ?  I mean, according to the position some "rules" might be applied to determine a unique piece square table !?  Those rules may act as some kind of pre-processor for the position ..

NOTE: you might take a look at the PeSTo engine : http://rofchade.nl/?p=307

**Comment by TerjeKir** [comment]
I save the midgame and endgame scores in 1 integer (idea seen in SF, Ethereal and others). A value of S( 52, 76) means 52 for midgame and 76 for endgame for example, thus the single table effectively holds 2 tables :)

Compiled on my machine and stripped of symbols it is 92 Kb :D

**Comment by tissatussa** [comment]
OK, but what about my idea of "dynamic" PST ?  Is it realistic ?

**Comment by TerjeKir** [comment]
Dynamic PSQTs, specifically using different ones when kings are castled opposite has been on my radar for a while and seems like a good idea. Weiss often seems clueless how to play in opposite castling and I think differnet PSQTs for that might be a good solution. There may be other situations too, but I haven't thought of any yet.

**Comment by tissatussa** [comment]
some thoughts about such dynamic PSQTs :
- amount of pieces
- amount of possible (piece) captures
- piece mobility, regarding pawns restricting it
- pawn influence in centre
- isolated pawn(s)
- passed pawn(s)
- ...

design factors to accomplish this ..

**Comment by TerjeKir** [comment]
Thanks for the idea, I'll be contemplating this going forward, but it might take a while to come up with something that works.

**Comment by tissatussa** [comment]
Thanks .. just be open .. i know, i'm a programmer too .. other points of view might help ..

some UCI option i found, is called "dynamic contempt" (true/false) .. what is that ?  could it match this issue ?

**Comment by TerjeKir** [comment]
Apologies, I seem to have missed the question here.

I think dynamic contempt means the engine gives all positions a bonus score when the engine thinks it is winning (or a malus when losing). Weiss does this (always on). I don't think it's related to dynamic PSQTs though.
