### ISSUE TITLE
thinking while only 1 legal move ?

### ISSUE THREAD

**Issue by tissatussa** [TerjeKir/weiss#500]
hi,

while testing your Weiss v1.5-dev i discover it's thinking 41 (!?) seconds to "find" the only legal move in this position :

![only_one_move](https://user-images.githubusercontent.com/1109281/125734440-b01eac40-6de3-48e1-bb66-411417956f1f.png)

i think you should be able to fix this issue ..

NOTE: Weiss is not the only engine which does this.

**Comment by TerjeKir** [comment]
Weiss will now spend at most half a second on forced moves :)
