### ISSUE TITLE
MultiPV 1 for best performance ?

### ISSUE THREAD

**Issue by tissatussa** [TerjeKir/weiss#611]
I remember you started implementing MultiPV in Weiss .. for me, using MultiPV has several advantages esp. when analysing a certain position .. it's being said, and also stated in your README, to set MultiPV 1 for best performance, but i wonder if that's true .. as an example i give this position from the game Polgar vs. Berkes, Budapest Hunguest Hotels 2003 :

![Polar-vs-Berkes=g4](https://user-images.githubusercontent.com/1109281/210069991-77e250db-540b-46fd-b2b1-d91eb4cc7f33.png)

r1bq1r1k/p1pnbpp1/1p2p3/6p1/3PB3/5N2/PPPQ1PPP/2KR3R w - - 0 14

White to move. Here White can take the Rook on a8, but the move g2-g4 !? is best .. Judith Polgar found this move and won that game! When i let engines think about this position (i use SCID on Linux) most of them do not find g4, esp. with MultiPV 1, which is the setting when at tournaments or even regular games in eg. CuteChess (i also learned CuteChess misbehaves when using MultiPV > 1) .. most engines don't even consider the move at any moment - but modern SF finds it instantly .. surely :-)

Also the newest compiled Weiss v2.1-dev does not find g4 being best move at MultiPV 1 : when i let it think for 1 minute it reaches depth 35 but only considers Bxa8. This "behaviour" differs at higher MultiPV, my screencast (edit, under 5 minutes) can illustrate this : we see Weiss v2.1-dev evaluating the position at several MultiPV, starting at 1, then 8, 6, 4, 3 and 2 .. you may be surprised :

https://user-images.githubusercontent.com/1109281/210070096-fe92fda7-28d8-441e-a9cd-df7e7ea17536.mp4

To me it seems a higher MultiPV forces an engine to consider other moves, which method then may soon (!) give a far superior best move : at first g4 had eval about -2, but finally it has about +2 !? This way of evaluating will not be perfect in all positions, but when using (some) MultiPV pruning seems better, although less high depth is reached because the engine needs CPU time to calculate all MultiPV moves ..

What are your thoughts about this ?

**Comment by TerjeKir** [comment]
Hey again, thanks for the continued interest!

For any position where the best move is hard to find and looks bad at shallow depths, using MultiPV high enough (or searchmoves <move>) to force the engine to look at the move more in depth will make it much more likely to see it. However, in the majority of positions this isn't the case, and MultiPV above 1 lowers strength. A test of 6000 games from back when I implemented it shows that MultiPV 3 loses about 200 elo vs MultiPV 1. So in general it is the case that MultiPV 1 is the best, but when trying to solve puzzles it can definitely help to try using a higher value.

Cool puzzle too by the way, Weiss here (1 thread, 1GB hash, MPV 1) switched to g4 at depth 37 after about 2 minutes - while it takes merely a few seconds with MultiPV 3! From what I can tell, there are 2 reasonable moves aside from g4 (Bxa8 and h4), so forcing the engine to look at the rest and pick a third best move quickly leads it to finding g4 as not only the 3rd best, but the best overall :)

**Comment by tissatussa** [comment]
> Hey again, thanks for the continued interest

yes, i still follow the development of Weiss .. i see you take a long time releasing a non-dev v2.1 .. nevermind, i have no problems with the latest dev .. this MPV thing intrigues me .. you described it well : when solving puzzles -we know some hidden solution exists- MPV can help .. so, could a position first be examined to determine if it could possibly be "a puzzle" ? Then adjust the eval algorithm according to that, esp. # MPV ..

btw. sometimes i stumble upon an UCI option called "Contempt" and even "Dynamic Contempt" .. i understand this is some "optimism", am i right? That way, g4 may also be considered ?

**Comment by TerjeKir** [comment]
Yeah, it's taken a long time to get 2.1 out - I've had less time for dev work and while dev is a good bit stronger than 2.0 I feel like some of the stuff I've added is only half-done. That said 2.1 should be out in a month or two I hope :)

It would be impressive if one was able to detect such positions, but I have no idea how to do it.

I believe contempt settings generally makes the engine prefer slightly worse positions over taking a known draw (say avoiding draw despite seeing the alternative as -20cp). Weiss doesn't support this so I'm not too familiar though.

**Comment by tissatussa** [comment]
> It would be impressive if one was able to detect such positions, but I have no idea how to do it

i have no idea either and i never saw such thing .. my question was meant to impose your reaction, because you're into engine programming, i'm not - just a user.

before closing this Issue, i want to put it this way :

i think now and then Weiss joins tournaments at TCEC and elsewhere .. some of them use longer time controls, eg. 30 minutes per player, so then it may be useful to apply MPV while evaluating : although reached depths will be lower, quality of "best moves" increases ? -- Tournament rules may forbid using MPV, but an evaluation algorithm can function like that, couldn't it ?

**Comment by TerjeKir** [comment]
Tournaments allow MultiPV so I could request them to set it to any value. Like we've discussed tho, in most situations it is much worse, so it would need some way to predict the likelyhood of MultiPV being useful in the current position. I can't think of a way to predict this tho.

**Comment by tissatussa** [comment]
> ..to predict the likelyhood of MultiPV being useful in the current position..

i will think about it .. out of the box :-)
thanks for the brainstorm!

**Comment by tissatussa** [comment]
-fin-
