### ISSUE TITLE
Bug in evaluation

### ISSUE THREAD

**Issue by Carbecq** [TerjeKir/weiss#715]
In file evaluate.c, line 293, You use FILE_A... instead of FileABB...

**Comment by TerjeKir** [comment]
Thanks for pointing this out! I've removed the bugged code as it had no effect on the end result, and will probably test adding back the corrected code to see if it's worth having there at all.

**Comment by TerjeKir** [comment]
Fixing this gained elo, thanks again for pointing it out :)
