### ISSUE TITLE
time management and complexity of the position

### ISSUE THREAD

**Issue by tissatussa** [TerjeKir/weiss#717]
i think these two can be related, because some positions need extra care .. here's an example in the "Norwegian Rat" opening (*) :

```
Start position : rnbqkb1r/pppppp1p/5np1/8/3PP3/8/PPP2PPP/RNBQKBNR w KQkq - 1 3

1.   e5 {+1.04/25  15s}  Nh5 {-0.44/38  23s}
2.  Nf3 {+1.03/29  30s}   d6 {-0.35/28  12s}
3.  Bc4 {+1.09/27  14s} dxe5 {-0.24/28  12s}
4. Nxe5 {+1.09/29  19s}   e6 {-0.27/29  15s}
5.  Be3 {+1.00/33  75s}  Bg7 {-0.31/27  11s}
6.  Nc3 {+0.95/32  27s}  Nd7 {-0.63/37 123s}

FEN : rnbqk2r/ppp2pbp/4p1p1/4N2n/2BP4/2N1B3/PPP2PPP/R2QK2R b KQkq - 3 8 
```

*) i think this is an invention of Magnus Carlsen, not sure though..

![black-played-Nd7-after-long-think](https://github.com/user-attachments/assets/bd278ec9-166f-4d3c-8cb9-47203a68d777)

Stockfish 16 HCE played Black in this 10m+5s game. Its 6th move was played after more then 2 minutes, much more then the other moves. Did SF consider the concept 'complexity of the position' here and decide to take more time ? Do some engines use this concept anyhow ? If so, does some formula exist to determine a 'complexity of the position' ?

What are your thoughts about this ?
Did you ever consider using this concept ?
(Or maybe this concept is not realistic, chess is complex)

**Comment by TerjeKir** [comment]
SF uses ideas that may be seen as proxies for complexity, for instance it will spend more time if the best move found constantly changes, while using much less time if it continually finds the same move to be the best. Weiss does something similar. It's hard to quantify complexity of a position, but heuristics like these area kind of proxy.

**Comment by tissatussa** [comment]
> ..spend more time if the best move found constantly changes..

well explained, in fact your answer is exactly what i imagined, thanks. I did not look into the SF code but i can imagine more complexity factors.
